version: "3.8"

services:
  replica1:
    build: ./replica1
    ports:
      - "5001:5001"
    volumes:
      - ./replica1:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/status"]
      interval: 5s
      timeout: 2s
      retries: 3

  replica2:
    build: ./replica2
    ports:
      - "5002:5002"
    volumes:
      - ./replica2:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/status"]
      interval: 5s
      timeout: 2s
      retries: 3

  replica3:
    build: ./replica3
    ports:
      - "5003:5003"
    volumes:
      - ./replica3:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/status"]
      interval: 5s
      timeout: 2s
      retries: 3

  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    volumes:
      - ./gateway:/app
      - ./frontend:/app/frontend
    depends_on:
      replica1:
        condition: service_healthy
      replica2:
        condition: service_healthy
      replica3:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/status"]
      interval: 5s
      timeout: 2s
      retries: 3
